const privateWebsites: any = [
    {
        ACG: {
            bilibili: 'http://www.bilibili.com',
            douyu: 'https://www.douyu.com/',
            niconico: 'http://www.nicovideo.jp/',
            u2b: 'https://www.youtube.com/',
            '4chan': 'http://www.4chan.org/',
            '2chan': 'http://www.2chan.net/',
            tumblr: 'https://www.tumblr.com/',
            steam: 'http://store.steampowered.com/',
            steamCN: 'https://steamcn.com/forum.php',
            bangumi: 'http://bangumi.tv/',
            acfun: 'http://www.acfun.tv/',
            thwiki: 'http://www.thwiki.cc/',
            pixiv: 'http://www.pixiv.net/',
            hpoi: 'http://www.hpoi.net/',
            saucenao: 'http://saucenao.com/',
            iqdb: 'http://iqdb.org/',
            safebooru: 'http://safebooru.org/',
            tineye: 'https://www.tineye.com/',
            Tbus: 'http://games.tgbus.com/pspcn/',
            dilidili: 'http://www.dilidili.wang/',
            osu: 'https://osu.ppy.sh/home',
            sankakucomplex: 'https://chan.sankakucomplex.com/',
            hacg: 'https://www.llss.fun/',
            steamcard: 'http://www.steamcardexchange.net/',
        },
        SNS: {
            weibo: 'http://weibo.com/',
            zhihu: 'https://www.zhihu.com/',
            twitch: 'https://go.twitch.tv/',
            wx: 'https://wx.qq.com/',
            t66y: 'https://t66y.com/index.php',
            quora: 'https://www.quora.com/#',
            douban: 'https://www.douban.com/',
            twitter: 'https://twitter.com/',
            linkedin: 'https://www.linkedin.com/',
            weixin: 'https://wx.qq.com/',
            V2EX: 'https://www.v2ex.com/',
            gmail: 'https://mail.google.com/mail/u/0/#inbox',
        },
        Techonology: {
            github: 'https://github.com/love999262',
            speedtest: 'http://www.speedtest.net/',
            leetcode: 'https://leetcode.com/',
            gitbooks: 'https://www.gitbook.com/',
            bandwagon: 'https://bwh1.net/',
            stackoverflow: 'http://stackoverflow.com/',
            typescript: 'https://www.typescriptlang.org/',
            tscn: 'https://www.tslang.cn/',
            w3schools: 'http://www.w3schools.com/',
            '$.api': 'http://api.jquery.com/',
            jshint: 'http://jshint.com/',
            jsfiddle: 'https://jsfiddle.net/',
            caniuse: 'http://caniuse.com/',
            jsonlint: 'https://jsonlint.com/',
            babel: 'http://babeljs.io/',
            nodejscn: 'http://nodejs.cn/',
            vue: 'https://cn.vuejs.org/',
            vueDoc: 'https://cn.vuejs.org/v2/guide/',
            vueAPI: 'https://cn.vuejs.org/v2/api/',
            webpackDoc: 'http://webpack.github.io/docs/',
            ReactCN: 'https://doc.react-china.org/',
            React: 'https://facebook.github.io/react/',
            'React-Router': 'http://react-guide.github.io/react-router-cn/',
            Redux: 'http://www.redux.org.cn/',
            pythonDoc: 'https://docs.python.org/3/',
            owasp: 'https://www.owasp.org',
            alexa: 'http://www.alexa.com/',
            qiniu: 'https://portal.qiniu.com/',

        },
        Shopping: {
            taobao: 'https://www.taobao.com/',
            JD: 'http://www.jd.com/',
            Amazon: 'http://www.amazon.cn/',
            smzdm: 'http://www.smzdm.com/',
            moebuy: 'http://www.030buy.net/',
            AmazonJP: 'https://www.amazon.co.jp/',
        },
        English: {
            bbc: 'http://www.bbc.co.uk/',
            voa: 'http://www.voa.com/',
            usatoday: 'http://www.usatoday.com/',
            latimes: 'http://www.latimes.com/',
            nytimes: 'http://www.nytimes.com/',
            washingtonpost: 'http://www.washingtonpost.com/',
            wsj: 'http://www.wsj.com/',
            nydailynews: 'http://www.nydailynews.com/',
            reddit: 'https://www.reddit.com/',
            imdb: 'http://www.imdb.com/',
            nypost: 'http://www.nypost.com/',
        },

    },
];


export default privateWebsites;
