const privateWebsites: any = [
    {
        ACG: {
            bilibili: 'http://www.bilibili.com',
            iqiyi: 'http://www.iqiyi.com/',
            vqq: 'https://v.qq.com/',
            youku: 'http://www.youku.com/',
            douyu: 'https://www.douyu.com/',
            niconico: 'http://www.nicovideo.jp/',
            u2b: 'https://www.youtube.com/',
            '4chan': 'http://www.4chan.org/',
            '2chan': 'http://www.2chan.net/',
            tumblr: 'https://www.tumblr.com/',
            u2bdl: 'https://youtubemultidownloader.com/',
            steam: 'http://store.steampowered.com/',
            steamCN: 'https://steamcn.com/forum.php',
            bangumi: 'http://bangumi.tv/',
            acfun: 'http://www.acfun.tv/',
            thwiki: 'http://www.thwiki.cc/',
            pixiv: 'http://www.pixiv.net/',
            hpoi: 'http://www.hpoi.net/',
            saucenao: 'http://saucenao.com/',
            iqdb: 'http://iqdb.org/',
            safebooru: 'http://safebooru.org/',
            tineye: 'https://www.tineye.com/',
            Tbus: 'http://games.tgbus.com/pspcn/',
            dilidili: 'http://www.dilidili.wang/',
            osu: 'https://osu.ppy.sh/home',
            sankakucomplex: 'https://chan.sankakucomplex.com/',
            hacg: 'https://www.llss.fun/',
            steamcard: 'http://www.steamcardexchange.net/',
        },
        SNS: {
            weibo: 'http://weibo.com/',
            zhihu: 'https://www.zhihu.com/',
            tianya: 'http://bbs.tianya.cn/',
            twitch: 'https://go.twitch.tv/',
            wx: 'https://wx.qq.com/',
            t66y: 'https://t66y.com/index.php',
            pornhub: 'https://www.pornhub.com',
            quora: 'https://www.quora.com/#',
            douban: 'https://www.douban.com/',
            twitter: 'https://twitter.com/',
            facebook: 'https://www.facebook.com/',
            linkedin: 'https://www.linkedin.com/',
            weixin: 'https://wx.qq.com/',
            V2EX: 'https://www.v2ex.com/',
            gmail: 'https://mail.google.com/mail/u/0/#inbox',
        },
        Techonology: {
            github: 'https://github.com/love999262',
            gitbooks: 'https://www.gitbook.com/',
            pdftoword: 'https://www.ilovepdf.com/pdf_to_word',
            juejin: 'https://juejin.im/timeline',
            'html-js': 'http://www.html-js.com/',
            UC: 'http://crop-answer.sm.cn/answer/index?activity=million&from=smball#/match/million',
            leetcode: 'https://leetcode.com/',
            leetcodeCN: 'https://leetcode-cn.com/',
            imooc: 'http://www.imooc.com',
            study163: 'http://study.163.com/',
            speedtest: 'http://www.speedtest.net/',
            savefrom: 'https://en.savefrom.net/',
            bandwagon: 'https://bwh1.net/',
            cnblogs: 'https://www.cnblogs.com/',
            stackoverflow: 'http://stackoverflow.com/',
            typescript: 'https://www.typescriptlang.org/',
            tscn: 'https://www.tslang.cn/',
            w3schools: 'http://www.w3schools.com/',
            '$.api': 'http://api.jquery.com/',
            jshint: 'http://jshint.com/',
            jsfiddle: 'https://jsfiddle.net/',
            caniuse: 'http://caniuse.com/',
            jsonlint: 'https://jsonlint.com/',
            babel: 'http://babeljs.io/',
            nodejscn: 'http://nodejs.cn/',
            vue: 'http://cn.vuejs.org/v2/api/',
            webpackCN: 'https://doc.webpack-china.org/',
            vueDoc: 'https://cn.vuejs.org/v2/guide/',
            vueAPI: 'https://cn.vuejs.org/v2/api/',
            webpackDoc: 'http://webpack.github.io/docs/',
            ReactCN: 'https://doc.react-china.org/',
            React: 'https://facebook.github.io/react/',
            'React-Router': 'http://react-guide.github.io/react-router-cn/',
            Redux: 'http://www.redux.org.cn/',
            pythonDoc: 'https://docs.python.org/3/',
            owasp: 'https://www.owasp.org',
        
            alexa: 'http://www.alexa.com/',
            qiniu: 'https://portal.qiniu.com/',

        },
        Shopping: {
            taobao: 'https://www.taobao.com/',
            JD: 'http://www.jd.com/',
            Amazon: 'http://www.amazon.cn/',
            meituan: 'https://sh.meituan.com/',
            dianping: 'https://www.dianping.com/',
            smzdm: 'http://www.smzdm.com/',
            moebuy: 'http://www.030buy.net/',
            AmazonJP: 'https://www.amazon.co.jp/',
        },
        English: {
            bbc: 'http://www.bbc.co.uk/',
            voa: 'http://www.voa.com/',
            usatoday: 'http://www.usatoday.com/',
            latimes: 'http://www.latimes.com/',
            nytimes: 'http://www.nytimes.com/',
            washingtonpost: 'http://www.washingtonpost.com/',
            wsj: 'http://www.wsj.com/',
            nydailynews: 'http://www.nydailynews.com/',
            reddit: 'https://www.reddit.com/',
            imdb: 'http://www.imdb.com/',
            nypost: 'http://www.nypost.com/',
        },
        Others: {
            exmail: 'https://exmail.qq.com/',
            hotmail: 'https://outlook.live.com/owa/',
            xvcams: 'http://xvcams.com',
            icloud: 'https://www.icloud.com',
            myfreecams: 'https://www.myfreecams.com/',
            gmail: 'https://mail.google.com/mail/u/0/#inbox',
            'iconfont.cn': 'http://www.iconfont.cn/',
            tinypng: 'https://tinypng.com/',
            giphy: 'http://giphy.com/',
            alexa: 'http://www.alexa.com/',
            qiniu: 'https://portal.qiniu.com/',
        },
    },
];


export default privateWebsites;
